### ISSUE TITLE
Ummm... What?

### ISSUE THREAD

**Issue by macmeister1967** [NayamAmarshe/gameready#10]
Your entire explanation is nothing but emulation layers and emulation tools to run Windows games...

You do know there are Linux games that are native, right?

**Comment by NayamAmarshe** [comment]
I'm sorry but how does this relate to gameready? It's a wiki for beginners who want to know about Proton/Lutris gaming terminology. Native linux gaming doesn't require these things and not the focus of this project.

**Comment by macmeister1967** [comment]
sorry, my bad.

Saw this on reddit and it was described very differently.

Again, my apologies.

C.

**Comment by NayamAmarshe** [comment]
> sorry, my bad.
> 
> Saw this on reddit and it was described very differently.
> 
> Again, my apologies.
> 
> C.
> 

No worries :)
