### ISSUE TITLE
No update for winetricks

### ISSUE THREAD

**Issue by chxei** [NayamAmarshe/gameready#11]
https://github.com/NayamAmarshe/gameready/blob/4d21fbfa4f7eb2775f62d4fcc159e5dc9784de23/gameready.sh#L31-L33

That's not the best way to install winetricks, basically, you are doomed on the same version. You either install it through some kind of package manager or repo, or include `winetricks --self-update`  command somewhere to keep it updated.

**Comment by NayamAmarshe** [comment]
Ah got it. These instructions were actually taken from the WINE website. I'll see what I can do about this. Thank you!

**Comment by NayamAmarshe** [comment]
Fixed!
