### ISSUE TITLE
No need for hardcoded version number

### ISSUE THREAD

**Issue by chxei** [NayamAmarshe/gameready#12]
https://github.com/NayamAmarshe/gameready/blob/4d21fbfa4f7eb2775f62d4fcc159e5dc9784de23/gameready.sh#L50

you can get the latest release version number with something like this:
➜ latestversion=$(git ls-remote --tags https://github.com/FeralInteractive/gamemode.git | tail -n 1 | cut -d/ -f3-);

**Comment by NayamAmarshe** [comment]
Fixed :D
