### ISSUE TITLE
Typo in the release tag

### ISSUE THREAD

**Issue by Lrss** [NayamAmarshe/gameready#2]
Your version tag is wrongly spelled "gamready" in https://github.com/NayamAmarshe/gameready/tags

**Comment by Lrss** [comment]
You should properly also name it a version name instead of just gameready, because when repository source code is downloaded the folder is going to be named `[repository_name]-[tag]`, so it looks weird with gameready-gameready.

**Comment by NayamAmarshe** [comment]
Done, thanks for reporting 😄
I actually wasn't expecting to ever update the script but I think we can help Arch and Fedora users too.
