### ISSUE TITLE
Need Arch Linux Support 

### ISSUE THREAD

**Issue by yasindce1998** [NayamAmarshe/gameready#3]
Kindly create a support script for arch Linux.

**Comment by NayamAmarshe** [comment]
Yes, that is planned. I'll try to add it as soon as I get time :)

**Comment by ksharizard** [comment]
Hi! I am willing to work on the script if you haven't started work on it.

**Comment by NayamAmarshe** [comment]
> Hi! I am willing to work on the script if you haven't started work on it.

Yeah, I haven't yet 😅 I'm busy with other things at the moment.
