### ISSUE TITLE
Wine as an acronym

### ISSUE THREAD

**Issue by IcyAlmond** [NayamAmarshe/gameready#9]
https://www.winehq.org/about says that it was originally an acronym and spells it with capital casing.
> Wine (originally an acronym for "Wine Is Not an Emulator")

And that's also what is currently accepted by the Wikipedia page for wine https://wikipedia.org/wiki/Wine_(software).

**Comment by NayamAmarshe** [comment]
Hi, sorry didn't understand. Why did you create this issue?

**Comment by IcyAlmond** [comment]
I mean that it no longer stands for "Wine Is Not an Emulator" and it is just "Wine" now

**Comment by NayamAmarshe** [comment]
> I mean that it no longer stands for "Wine Is Not an Emulator" and it is just "Wine" now

Alright, I'll edit the wiki. Thanks!
